name: buildx

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  TARGET_IMAGE: ghcr.io/by275/restic

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Initial Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.TARGET_IMAGE }}:testing
          platforms: linux/amd64,linux/arm/v7,linux/arm64
      -
        name: Load and Get Variables
        run: |
          docker buildx build \
            -t ${{ env.TARGET_IMAGE }}:testing \
            --platform=linux/amd64 \
            --load \
            .
          VER_FULL=$(docker run --rm ${{ env.TARGET_IMAGE }}:testing version | awk '{print $2}')
          echo "VER_FULL=$VER_FULL" >> $GITHUB_ENV
          VER_MINOR=$(echo $VER_FULL | cut -d. -f-2)
          echo "VER_MINOR=$VER_MINOR" >> $GITHUB_ENV
          VER_MAJOR=$(echo $VER_FULL | cut -d. -f-1)
          echo "VER_MAJOR=$VER_MAJOR" >> $GITHUB_ENV
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Buildx and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.TARGET_IMAGE }}:latest
            ${{ env.TARGET_IMAGE }}:${{ env.VER_FULL }}
            ${{ env.TARGET_IMAGE }}:${{ env.VER_MINOR }}
            ${{ env.TARGET_IMAGE }}:${{ env.VER_MAJOR }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
      -
        name: Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            ${{ env.TARGET_IMAGE }}:latest
            ${{ env.TARGET_IMAGE }}:${{ env.VER_FULL }}
            ${{ env.TARGET_IMAGE }}:${{ env.VER_MINOR }}
            ${{ env.TARGET_IMAGE }}:${{ env.VER_MAJOR }}
